{
 "title": "Heizung",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vorlauftemperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heater_degree{}" }
   ]
  },
  {
   "title": "Rücklauftemperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heater_return_degree{}" }
   ]
  },
  {
   "title": "Volumenstrom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heater_volume{}" }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outside_degree{}" }
   ]
  },
  {
   "title": "Temperaturverlauf",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "heater_degree", "legendFormat": "Vorlauftemperatur" },
    { "expr": "outside_degree", "legendFormat": "Außentemperatur" },
    { "expr": "water_degree", "legendFormat": "Warmwasser" },
    { "expr": "circuit_degree", "legendFormat": "Heizkreis" },
    { "expr": "heater_return_degree", "legendFormat": "Rücklauftemperatur" }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "water_degree{}" }
   ]
  },
  {
   "title": "Heizkreis Vorlauf",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "circuit_degree{}" }
   ]
  }
 ]
}